apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-notes-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: securenotes.local # Modify for production domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secure-notes-service
                port:
                  number: 80
